# Generated by Django 4.0.6 on 2022-09-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionName', models.CharField(max_length=100)),
                ('competitionDescription', models.TextField()),
                ('competitionImage1', models.ImageField(default='dcomp1.jpg', upload_to='competition_pics')),
                ('competitionImage2', models.ImageField(default='dcomp2.jpg', upload_to='competition_pics')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('cityImage', models.ImageField(default='dcity.jpg', upload_to='city_pics')),
                ('cityCompetitions', models.ManyToManyField(to='city.competition')),
            ],
        ),
    ]
