# Generated by Django 4.0.6 on 2022-09-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_team_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='group',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='city.applicant'),
        ),
    ]
