# Generated by Django 4.1 on 2022-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='competitions',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='competitions',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='competitions',
        ),
        migrations.AddField(
            model_name='person',
            name='Contactno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='field',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
