# Generated by Django 4.1 on 2022-09-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_rename_country_competitions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='competitions',
        ),
        migrations.AddField(
            model_name='competitions',
            name='competitions',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='persons.city'),
            preserve_default=False,
        ),
    ]
