# Generated by Django 4.1 on 2022-09-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_remove_city_competitions_competitions_competitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='competitions',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.competitions'),
        ),
    ]
