# Generated by Django 4.1 on 2022-09-07 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_person_competitions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='competitions',
            new_name='Competition',
        ),
        migrations.RemoveField(
            model_name='person',
            name='competitions',
        ),
        migrations.AddField(
            model_name='person',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.competition'),
        ),
    ]
