# Generated by Django 4.1 on 2022-09-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_rename_competitions_competition_competition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='competition',
            new_name='city',
        ),
    ]
