# Generated by Django 4.0.6 on 2022-09-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(choices=[('delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad')], default='delhi', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionName', models.CharField(choices=[('dance', 'Dance'), ('Music', 'music'), ('arts', 'Arts')], default='Arts', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Emailid', models.EmailField(max_length=500)),
                ('Competition', models.ForeignKey(choices=[('dance', 'Dance'), ('Music', 'music'), ('arts', 'Arts')], default='Arts', on_delete=django.db.models.deletion.CASCADE, to='projectApp.competition')),
                ('city', models.ForeignKey(choices=[('delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad')], default='delhi', on_delete=django.db.models.deletion.CASCADE, to='projectApp.city')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.group')),
            ],
        ),
    ]
